-- MySQL Script generated by MySQL Workbench
-- Sat 11 Feb 2017 01:02:18 PM COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_eros
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_eros` ;

-- -----------------------------------------------------
-- Schema bd_eros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_eros` DEFAULT CHARACTER SET utf8 COLLATE utf8_persian_ci ;
USE `bd_eros` ;

-- -----------------------------------------------------
-- Table `bd_eros`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellidos` VARCHAR(100) NULL,
  `tel` VARCHAR(25) NULL,
  `cel` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  `usuario` VARCHAR(100) NULL,
  `contra` VARCHAR(10) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`tipo_anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`tipo_anuncio` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`tipo_anuncio` (
  `idtipo_anuncio` INT NOT NULL,
  `tipo` VARCHAR(25) NULL,
  PRIMARY KEY (`idtipo_anuncio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`dep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`dep` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`dep` (
  `iddep` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`iddep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`mun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`mun` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`mun` (
  `idmun` INT NOT NULL,
  `iddep` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmun`, `iddep`),
  INDEX `fk_poblacion_departamento1_idx` (`iddep` ASC),
  CONSTRAINT `fk_poblacion_departamento1`
    FOREIGN KEY (`iddep`)
    REFERENCES `bd_eros`.`dep` (`iddep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`promocion` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`promocion` (
  `promocion` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`promocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`anuncio` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`anuncio` (
  `idanuncio` INT NOT NULL AUTO_INCREMENT,
  `tipo_anuncio` INT NOT NULL,
  `titulo` VARCHAR(200) NULL,
  `texto` MEDIUMTEXT NULL,
  `edad` VARCHAR(3) NULL,
  `altura` VARCHAR(3) NULL,
  `usuario` INT NULL,
  `tarifa` VARCHAR(7) NULL,
  `email` VARCHAR(100) NULL,
  `tel` VARCHAR(25) NULL,
  `web` VARCHAR(100) NULL,
  `mun_idmun` INT NOT NULL,
  `mun_iddep` INT NOT NULL,
  `barrio` VARCHAR(100) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `promocion_promocion` INT NULL,
  PRIMARY KEY (`idanuncio`),
  INDEX `fk_anuncio_usuario_idx` (`usuario` ASC),
  INDEX `fk_anuncio_tipo_anuncio1_idx` (`tipo_anuncio` ASC),
  INDEX `fk_anuncio_mun1_idx` (`mun_idmun` ASC, `mun_iddep` ASC),
  INDEX `fk_anuncio_promocion1_idx` (`promocion_promocion` ASC),
  CONSTRAINT `fk_anuncio_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `bd_eros`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_tipo_anuncio1`
    FOREIGN KEY (`tipo_anuncio`)
    REFERENCES `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_mun1`
    FOREIGN KEY (`mun_idmun` , `mun_iddep`)
    REFERENCES `bd_eros`.`mun` (`idmun` , `iddep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_promocion1`
    FOREIGN KEY (`promocion_promocion`)
    REFERENCES `bd_eros`.`promocion` (`promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_eros`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_eros`.`imagen` ;

CREATE TABLE IF NOT EXISTS `bd_eros`.`imagen` (
  `idimagen` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NULL,
  `idanuncio` INT NOT NULL,
  PRIMARY KEY (`idimagen`),
  INDEX `fk_imagen_anuncio1_idx` (`idanuncio` ASC),
  CONSTRAINT `fk_imagen_anuncio1`
    FOREIGN KEY (`idanuncio`)
    REFERENCES `bd_eros`.`anuncio` (`idanuncio`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bd_eros`.`tipo_anuncio`
-- -----------------------------------------------------
START TRANSACTION;
USE `bd_eros`;
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (1, 'Escorts');
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (2, 'Masajes Eroticos');
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (3, 'Travestis');
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (4, 'Gays');
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (5, 'Gigolo');
INSERT INTO `bd_eros`.`tipo_anuncio` (`idtipo_anuncio`, `tipo`) VALUES (6, 'Web Cam');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bd_eros`.`promocion`
-- -----------------------------------------------------
START TRANSACTION;
USE `bd_eros`;
INSERT INTO `bd_eros`.`promocion` (`promocion`, `tipo`, `valor`) VALUES (1, 'basica', '0');

COMMIT;

