USE bd_eros;
insert into mun(idmun, iddep, nombre) values(344,5,'el encanto');
insert into mun(idmun, iddep, nombre) values(57,5,'la chorrera');
insert into mun(idmun, iddep, nombre) values(382,5,'la pedrera');
insert into mun(idmun, iddep, nombre) values(1071,5,'la victoria');
insert into mun(idmun, iddep, nombre) values(1118,5,'leticia');
insert into mun(idmun, iddep, nombre) values(34,5,'miriti-parana');
insert into mun(idmun, iddep, nombre) values(24,5,'puerto alegria');
insert into mun(idmun, iddep, nombre) values(119,5,'puerto arica');
insert into mun(idmun, iddep, nombre) values(654,5,'puerto nariño');
insert into mun(idmun, iddep, nombre) values(893,5,'puerto santander');
insert into mun(idmun, iddep, nombre) values(511,5,'tarapaca');
insert into mun(idmun, iddep, nombre) values(1123,1,'abejorral');
insert into mun(idmun, iddep, nombre) values(540,1,'abriaqui');
insert into mun(idmun, iddep, nombre) values(143,1,'alejandria');
insert into mun(idmun, iddep, nombre) values(756,1,'altamira');
insert into mun(idmun, iddep, nombre) values(436,1,'amaga');
insert into mun(idmun, iddep, nombre) values(126,1,'amalfi');
insert into mun(idmun, iddep, nombre) values(316,1,'andes');
insert into mun(idmun, iddep, nombre) values(305,1,'angelopolis');
insert into mun(idmun, iddep, nombre) values(104,1,'angostura');
insert into mun(idmun, iddep, nombre) values(1165,1,'anori');
insert into mun(idmun, iddep, nombre) values(266,1,'antioquia(santa fe de)');
insert into mun(idmun, iddep, nombre) values(904,1,'anza');
insert into mun(idmun, iddep, nombre) values(979,1,'apartado');
insert into mun(idmun, iddep, nombre) values(576,1,'arboletes');
insert into mun(idmun, iddep, nombre) values(788,1,'argelia');
insert into mun(idmun, iddep, nombre) values(74,1,'armenia');
insert into mun(idmun, iddep, nombre) values(147,1,'barbosa');
insert into mun(idmun, iddep, nombre) values(671,1,'bello');
insert into mun(idmun, iddep, nombre) values(2,1,'belmira');
insert into mun(idmun, iddep, nombre) values(317,1,'betania');
insert into mun(idmun, iddep, nombre) values(1022,1,'betulia');
insert into mun(idmun, iddep, nombre) values(713,1,'bolivar (ciudad)');
insert into mun(idmun, iddep, nombre) values(919,1,'briceno');
insert into mun(idmun, iddep, nombre) values(470,1,'buritica');
insert into mun(idmun, iddep, nombre) values(332,1,'caceres');
insert into mun(idmun, iddep, nombre) values(40,1,'caicedo');
insert into mun(idmun, iddep, nombre) values(66,1,'caldas');
insert into mun(idmun, iddep, nombre) values(238,1,'campamento');
insert into mun(idmun, iddep, nombre) values(76,1,'caracoli');
insert into mun(idmun, iddep, nombre) values(1129,1,'caramanta');
insert into mun(idmun, iddep, nombre) values(1156,1,'carepa');
insert into mun(idmun, iddep, nombre) values(957,1,'carmen de viboral');
insert into mun(idmun, iddep, nombre) values(683,1,'carolina');
insert into mun(idmun, iddep, nombre) values(517,1,'caucasia');
insert into mun(idmun, iddep, nombre) values(840,1,'cañasgordas');
insert into mun(idmun, iddep, nombre) values(48,1,'chigorodo');
insert into mun(idmun, iddep, nombre) values(710,1,'cisneros');
insert into mun(idmun, iddep, nombre) values(841,1,'cocorna');
insert into mun(idmun, iddep, nombre) values(357,1,'concepcion');
insert into mun(idmun, iddep, nombre) values(777,1,'concordia');
insert into mun(idmun, iddep, nombre) values(883,1,'copacabana');
insert into mun(idmun, iddep, nombre) values(593,1,'dabeiba');
insert into mun(idmun, iddep, nombre) values(1099,1,'don matias');
insert into mun(idmun, iddep, nombre) values(937,1,'ebejico');
insert into mun(idmun, iddep, nombre) values(1054,1,'el bagre');
insert into mun(idmun, iddep, nombre) values(479,1,'entrerrios');
insert into mun(idmun, iddep, nombre) values(689,1,'envigado');
insert into mun(idmun, iddep, nombre) values(1101,1,'fredonia');
insert into mun(idmun, iddep, nombre) values(135,1,'frontino');
insert into mun(idmun, iddep, nombre) values(13,1,'giraldo');
insert into mun(idmun, iddep, nombre) values(1021,1,'girardota');
insert into mun(idmun, iddep, nombre) values(339,1,'gomez plata');
insert into mun(idmun, iddep, nombre) values(917,1,'granada');
insert into mun(idmun, iddep, nombre) values(1032,1,'guadalupe');
insert into mun(idmun, iddep, nombre) values(458,1,'guarne');
insert into mun(idmun, iddep, nombre) values(519,1,'guatape');
insert into mun(idmun, iddep, nombre) values(658,1,'heliconia');
insert into mun(idmun, iddep, nombre) values(504,1,'hispania');
insert into mun(idmun, iddep, nombre) values(908,1,'itagui');
insert into mun(idmun, iddep, nombre) values(315,1,'ituango');
insert into mun(idmun, iddep, nombre) values(787,1,'jardin');
insert into mun(idmun, iddep, nombre) values(926,1,'jerico');
insert into mun(idmun, iddep, nombre) values(432,1,'la ceja');
insert into mun(idmun, iddep, nombre) values(520,1,'la estrella');
insert into mun(idmun, iddep, nombre) values(318,1,'la pintada');
insert into mun(idmun, iddep, nombre) values(219,1,'la union');
insert into mun(idmun, iddep, nombre) values(515,1,'liborina');
insert into mun(idmun, iddep, nombre) values(261,1,'maceo');
insert into mun(idmun, iddep, nombre) values(704,1,'marinilla');
insert into mun(idmun, iddep, nombre) values(1027,1,'medellin');
insert into mun(idmun, iddep, nombre) values(174,1,'montebello');
insert into mun(idmun, iddep, nombre) values(323,1,'murindo');
insert into mun(idmun, iddep, nombre) values(930,1,'mutata');
insert into mun(idmun, iddep, nombre) values(851,1,'nariño');
insert into mun(idmun, iddep, nombre) values(204,1,'nechi');
insert into mun(idmun, iddep, nombre) values(379,1,'necocli');
insert into mun(idmun, iddep, nombre) values(1012,1,'olaya');
insert into mun(idmun, iddep, nombre) values(170,1,'peque');
insert into mun(idmun, iddep, nombre) values(150,1,'peñol');
insert into mun(idmun, iddep, nombre) values(1169,1,'por definir');
insert into mun(idmun, iddep, nombre) values(903,1,'pueblorrico');
insert into mun(idmun, iddep, nombre) values(128,1,'puerto berrio');
insert into mun(idmun, iddep, nombre) values(837,1,'puerto nare (la magdalena)');
insert into mun(idmun, iddep, nombre) values(1140,1,'puerto triunfo');
insert into mun(idmun, iddep, nombre) values(330,1,'remedios');
insert into mun(idmun, iddep, nombre) values(944,1,'retiro');
insert into mun(idmun, iddep, nombre) values(697,1,'rionegro');
insert into mun(idmun, iddep, nombre) values(10,1,'sabanalarga');
insert into mun(idmun, iddep, nombre) values(442,1,'sabaneta');
insert into mun(idmun, iddep, nombre) values(1143,1,'salgar');
insert into mun(idmun, iddep, nombre) values(943,1,'san andres');
insert into mun(idmun, iddep, nombre) values(248,1,'san carlos');
insert into mun(idmun, iddep, nombre) values(569,1,'san cristobal');
insert into mun(idmun, iddep, nombre) values(136,1,'san francisco');
insert into mun(idmun, iddep, nombre) values(617,1,'san jeronimo');
insert into mun(idmun, iddep, nombre) values(191,1,'san jose de la monta?a');
insert into mun(idmun, iddep, nombre) values(638,1,'san juan de uraba');
insert into mun(idmun, iddep, nombre) values(912,1,'san luis');
insert into mun(idmun, iddep, nombre) values(538,1,'san pedro');
insert into mun(idmun, iddep, nombre) values(982,1,'san pedro de uraba');
insert into mun(idmun, iddep, nombre) values(337,1,'san rafael');
insert into mun(idmun, iddep, nombre) values(861,1,'san roque');
insert into mun(idmun, iddep, nombre) values(573,1,'san vicente');
insert into mun(idmun, iddep, nombre) values(572,1,'santa barbara');
insert into mun(idmun, iddep, nombre) values(641,1,'santa rosa de osos');
insert into mun(idmun, iddep, nombre) values(932,1,'santo domingo');
insert into mun(idmun, iddep, nombre) values(940,1,'santuario');
insert into mun(idmun, iddep, nombre) values(1042,1,'segovia');
insert into mun(idmun, iddep, nombre) values(237,1,'sonson');
insert into mun(idmun, iddep, nombre) values(15,1,'sopetran');
insert into mun(idmun, iddep, nombre) values(413,1,'tamesis');
insert into mun(idmun, iddep, nombre) values(115,1,'taraza');
insert into mun(idmun, iddep, nombre) values(185,1,'tarso');
insert into mun(idmun, iddep, nombre) values(291,1,'titiribi');
insert into mun(idmun, iddep, nombre) values(1098,1,'toledo');
insert into mun(idmun, iddep, nombre) values(325,1,'turbo');
insert into mun(idmun, iddep, nombre) values(284,1,'uramita');
insert into mun(idmun, iddep, nombre) values(478,1,'urrao');
insert into mun(idmun, iddep, nombre) values(139,1,'valdivia');
insert into mun(idmun, iddep, nombre) values(764,1,'valparaiso');
insert into mun(idmun, iddep, nombre) values(1077,1,'vegachi');
insert into mun(idmun, iddep, nombre) values(718,1,'venecia');
insert into mun(idmun, iddep, nombre) values(888,1,'vigia del fuerte');
insert into mun(idmun, iddep, nombre) values(18,1,'yali');
insert into mun(idmun, iddep, nombre) values(1004,1,'yarumal');
insert into mun(idmun, iddep, nombre) values(1161,1,'yolombo');
insert into mun(idmun, iddep, nombre) values(1125,1,'yondo (casabe)');
insert into mun(idmun, iddep, nombre) values(408,1,'zaragoza');
insert into mun(idmun, iddep, nombre) values(1030,33,'arauca');
insert into mun(idmun, iddep, nombre) values(142,33,'arauquita');
insert into mun(idmun, iddep, nombre) values(201,33,'cravo norte');
insert into mun(idmun, iddep, nombre) values(425,33,'fortul');
insert into mun(idmun, iddep, nombre) values(1139,33,'puerto rondon');
insert into mun(idmun, iddep, nombre) values(1215,33,'saravena');
insert into mun(idmun, iddep, nombre) values(481,33,'saravena');
insert into mun(idmun, iddep, nombre) values(196,33,'tame');
insert into mun(idmun, iddep, nombre) values(866,36,'baranoa');
insert into mun(idmun, iddep, nombre) values(1126,36,'barranquilla');
insert into mun(idmun, iddep, nombre) values(138,36,'campo de la cruz');
insert into mun(idmun, iddep, nombre) values(815,36,'candelaria');
insert into mun(idmun, iddep, nombre) values(225,36,'galapa');
insert into mun(idmun, iddep, nombre) values(870,36,'juan de acosta');
insert into mun(idmun, iddep, nombre) values(687,36,'luruaco');
insert into mun(idmun, iddep, nombre) values(221,36,'malambo');
insert into mun(idmun, iddep, nombre) values(807,36,'manati');
insert into mun(idmun, iddep, nombre) values(803,36,'palmar de varela');
insert into mun(idmun, iddep, nombre) values(69,36,'piojo');
insert into mun(idmun, iddep, nombre) values(545,36,'piojo 2');
insert into mun(idmun, iddep, nombre) values(645,36,'polonuevo');
insert into mun(idmun, iddep, nombre) values(130,36,'ponedera');
insert into mun(idmun, iddep, nombre) values(551,36,'puerto colombia');
insert into mun(idmun, iddep, nombre) values(692,36,'repelon');
insert into mun(idmun, iddep, nombre) values(1124,36,'sabanagrande');
insert into mun(idmun, iddep, nombre) values(674,36,'sabanalarga');
insert into mun(idmun, iddep, nombre) values(988,36,'santa lucia');
insert into mun(idmun, iddep, nombre) values(31,36,'santo  tomas');
insert into mun(idmun, iddep, nombre) values(967,36,'soledad');
insert into mun(idmun, iddep, nombre) values(321,36,'suan');
insert into mun(idmun, iddep, nombre) values(561,36,'tubara');
insert into mun(idmun, iddep, nombre) values(1079,36,'usiacuri');
insert into mun(idmun, iddep, nombre) values(1028,29,'bogota d.c.');
insert into mun(idmun, iddep, nombre) values(83,3,'achi');
insert into mun(idmun, iddep, nombre) values(395,3,'alto del rosario');
insert into mun(idmun, iddep, nombre) values(267,3,'arenal');
insert into mun(idmun, iddep, nombre) values(102,3,'arjona');
insert into mun(idmun, iddep, nombre) values(414,3,'arroyohondo');
insert into mun(idmun, iddep, nombre) values(644,3,'barranco de loba');
insert into mun(idmun, iddep, nombre) values(1055,3,'calamar');
insert into mun(idmun, iddep, nombre) values(405,3,'canta gallo');
insert into mun(idmun, iddep, nombre) values(1109,3,'cartagena');
insert into mun(idmun, iddep, nombre) values(155,3,'cicuco');
insert into mun(idmun, iddep, nombre) values(287,3,'clemencia');
insert into mun(idmun, iddep, nombre) values(882,3,'cordoba');
insert into mun(idmun, iddep, nombre) values(64,3,'el carmen de bolivar');
insert into mun(idmun, iddep, nombre) values(70,3,'el guamo');
insert into mun(idmun, iddep, nombre) values(97,3,'el pe?on');
insert into mun(idmun, iddep, nombre) values(423,3,'hatillo de loba');
insert into mun(idmun, iddep, nombre) values(1069,3,'magangue');
insert into mun(idmun, iddep, nombre) values(222,3,'mahates');
insert into mun(idmun, iddep, nombre) values(707,3,'margarita');
insert into mun(idmun, iddep, nombre) values(632,3,'maria la baja');
insert into mun(idmun, iddep, nombre) values(84,3,'mompos');
insert into mun(idmun, iddep, nombre) values(278,3,'montecristo');
insert into mun(idmun, iddep, nombre) values(283,3,'morales');
insert into mun(idmun, iddep, nombre) values(68,3,'pinillos');
insert into mun(idmun, iddep, nombre) values(962,3,'regidor');
insert into mun(idmun, iddep, nombre) values(846,3,'rio viejo');
insert into mun(idmun, iddep, nombre) values(465,3,'san cristobal');
insert into mun(idmun, iddep, nombre) values(942,3,'san estanislao');
insert into mun(idmun, iddep, nombre) values(516,3,'san fernando');
insert into mun(idmun, iddep, nombre) values(1115,3,'san jacinto');
insert into mun(idmun, iddep, nombre) values(430,3,'san jacinto del cauca');
insert into mun(idmun, iddep, nombre) values(306,3,'san juan nepomuceno');
insert into mun(idmun, iddep, nombre) values(336,3,'san martin de loba');
insert into mun(idmun, iddep, nombre) values(864,3,'san pablo');
insert into mun(idmun, iddep, nombre) values(499,3,'santa catalina');
insert into mun(idmun, iddep, nombre) values(844,3,'santa rosa');
insert into mun(idmun, iddep, nombre) values(103,3,'santa rosa del sur');
insert into mun(idmun, iddep, nombre) values(791,3,'simiti');
insert into mun(idmun, iddep, nombre) values(124,3,'soplaviento');
insert into mun(idmun, iddep, nombre) values(563,3,'talaigua nueva');
insert into mun(idmun, iddep, nombre) values(52,3,'tiquisio (puerto rico)');
insert into mun(idmun, iddep, nombre) values(427,3,'turbaco');
insert into mun(idmun, iddep, nombre) values(699,3,'turbana');
insert into mun(idmun, iddep, nombre) values(884,3,'villanueva');
insert into mun(idmun, iddep, nombre) values(1046,3,'zambrano');
insert into mun(idmun, iddep, nombre) values(1007,27,'almeida');
insert into mun(idmun, iddep, nombre) values(804,27,'aquitania');
insert into mun(idmun, iddep, nombre) values(531,27,'arcabuco');
insert into mun(idmun, iddep, nombre) values(1152,27,'belen');
insert into mun(idmun, iddep, nombre) values(301,27,'belencito');
insert into mun(idmun, iddep, nombre) values(172,27,'berbeo');
insert into mun(idmun, iddep, nombre) values(1063,27,'beteitiva');
insert into mun(idmun, iddep, nombre) values(549,27,'boavita');
insert into mun(idmun, iddep, nombre) values(6,27,'boyaca');
insert into mun(idmun, iddep, nombre) values(1131,27,'briceno');
insert into mun(idmun, iddep, nombre) values(998,27,'buenavista');
insert into mun(idmun, iddep, nombre) values(1087,27,'busbanza');
insert into mun(idmun, iddep, nombre) values(877,27,'caldas');
insert into mun(idmun, iddep, nombre) values(328,27,'campohermoso');
insert into mun(idmun, iddep, nombre) values(650,27,'cerinza');
insert into mun(idmun, iddep, nombre) values(46,27,'chinavita');
insert into mun(idmun, iddep, nombre) values(257,27,'chiquinquira');
insert into mun(idmun, iddep, nombre) values(905,27,'chiquiza');
insert into mun(idmun, iddep, nombre) values(58,27,'chiscas');
insert into mun(idmun, iddep, nombre) values(694,27,'chita');
insert into mun(idmun, iddep, nombre) values(411,27,'chitaraque');
insert into mun(idmun, iddep, nombre) values(298,27,'chivata');
insert into mun(idmun, iddep, nombre) values(389,27,'chivor');
insert into mun(idmun, iddep, nombre) values(491,27,'cienega');
insert into mun(idmun, iddep, nombre) values(193,27,'combita');
insert into mun(idmun, iddep, nombre) values(858,27,'coper');
insert into mun(idmun, iddep, nombre) values(521,27,'corrales');
insert into mun(idmun, iddep, nombre) values(101,27,'covarachia');
insert into mun(idmun, iddep, nombre) values(612,27,'cubara');
insert into mun(idmun, iddep, nombre) values(299,27,'cucaita');
insert into mun(idmun, iddep, nombre) values(488,27,'cuitiva');
insert into mun(idmun, iddep, nombre) values(796,27,'duitama');
insert into mun(idmun, iddep, nombre) values(62,27,'el cocuy');
insert into mun(idmun, iddep, nombre) values(72,27,'el espino');
insert into mun(idmun, iddep, nombre) values(969,27,'firavitoba');
insert into mun(idmun, iddep, nombre) values(960,27,'floresta');
insert into mun(idmun, iddep, nombre) values(589,27,'gachantiva');
insert into mun(idmun, iddep, nombre) values(226,27,'gameza');
insert into mun(idmun, iddep, nombre) values(177,27,'garagoa');
insert into mun(idmun, iddep, nombre) values(685,27,'guacamayas');
insert into mun(idmun, iddep, nombre) values(635,27,'guateque');
insert into mun(idmun, iddep, nombre) values(350,27,'guayata');
insert into mun(idmun, iddep, nombre) values(773,27,'guican');
insert into mun(idmun, iddep, nombre) values(439,27,'iza');
insert into mun(idmun, iddep, nombre) values(206,27,'jenesano');
insert into mun(idmun, iddep, nombre) values(928,27,'jerico');
insert into mun(idmun, iddep, nombre) values(556,27,'la capilla');
insert into mun(idmun, iddep, nombre) values(584,27,'la uvita');
insert into mun(idmun, iddep, nombre) values(108,27,'la victoria');
insert into mun(idmun, iddep, nombre) values(606,27,'labranzagrande');
insert into mun(idmun, iddep, nombre) values(240,27,'macanal');
insert into mun(idmun, iddep, nombre) values(631,27,'maripi');
insert into mun(idmun, iddep, nombre) values(1019,27,'miraflores');
insert into mun(idmun, iddep, nombre) values(754,27,'mongua');
insert into mun(idmun, iddep, nombre) values(245,27,'mongui');
insert into mun(idmun, iddep, nombre) values(728,27,'moniquira');
insert into mun(idmun, iddep, nombre) values(897,27,'motavita');
insert into mun(idmun, iddep, nombre) values(936,27,'muzo');
insert into mun(idmun, iddep, nombre) values(188,27,'nobsa');
insert into mun(idmun, iddep, nombre) values(924,27,'nuevo colon');
insert into mun(idmun, iddep, nombre) values(400,27,'oicata');
insert into mun(idmun, iddep, nombre) values(996,27,'otanche');
insert into mun(idmun, iddep, nombre) values(946,27,'pachavita');
insert into mun(idmun, iddep, nombre) values(343,27,'paez');
insert into mun(idmun, iddep, nombre) values(527,27,'paipa');
insert into mun(idmun, iddep, nombre) values(45,27,'pajarito');
insert into mun(idmun, iddep, nombre) values(1154,27,'panqueba');
insert into mun(idmun, iddep, nombre) values(592,27,'pauna');
insert into mun(idmun, iddep, nombre) values(105,27,'paya');
insert into mun(idmun, iddep, nombre) values(790,27,'paz de rio');
insert into mun(idmun, iddep, nombre) values(574,27,'pesca');
insert into mun(idmun, iddep, nombre) values(290,27,'pisva');
insert into mun(idmun, iddep, nombre) values(60,27,'puerto boyaca');
insert into mun(idmun, iddep, nombre) values(965,27,'quipama');
insert into mun(idmun, iddep, nombre) values(734,27,'ramiriqui');
insert into mun(idmun, iddep, nombre) values(847,27,'raquira');
insert into mun(idmun, iddep, nombre) values(211,27,'rondon');
insert into mun(idmun, iddep, nombre) values(26,27,'saboya');
insert into mun(idmun, iddep, nombre) values(675,27,'sachica');
insert into mun(idmun, iddep, nombre) values(1132,27,'samaca');
insert into mun(idmun, iddep, nombre) values(951,27,'san eduardo');
insert into mun(idmun, iddep, nombre) values(537,27,'san jose de pare');
insert into mun(idmun, iddep, nombre) values(338,27,'san luis de gaceno');
insert into mun(idmun, iddep, nombre) values(500,27,'san mateo');
insert into mun(idmun, iddep, nombre) values(595,27,'san miguel de sema');
insert into mun(idmun, iddep, nombre) values(418,27,'san pablo de borbur');
insert into mun(idmun, iddep, nombre) values(934,27,'santa maria');
insert into mun(idmun, iddep, nombre) values(377,27,'santa rosa de viterbo');
insert into mun(idmun, iddep, nombre) values(811,27,'santa sofia');
insert into mun(idmun, iddep, nombre) values(643,27,'santana');
insert into mun(idmun, iddep, nombre) values(495,27,'sativanorte');
insert into mun(idmun, iddep, nombre) values(1033,27,'sativasur');
insert into mun(idmun, iddep, nombre) values(599,27,'siachoque');
insert into mun(idmun, iddep, nombre) values(53,27,'soata');
insert into mun(idmun, iddep, nombre) values(1025,27,'socha');
insert into mun(idmun, iddep, nombre) values(21,27,'socota');
insert into mun(idmun, iddep, nombre) values(347,27,'sogamoso');
insert into mun(idmun, iddep, nombre) values(14,27,'somondoco');
insert into mun(idmun, iddep, nombre) values(1013,27,'sora');
insert into mun(idmun, iddep, nombre) values(637,27,'soraca');
insert into mun(idmun, iddep, nombre) values(666,27,'sotaquira');
insert into mun(idmun, iddep, nombre) values(265,27,'susacon');
insert into mun(idmun, iddep, nombre) values(274,27,'sutamarchan');
insert into mun(idmun, iddep, nombre) values(1034,27,'sutatenza');
insert into mun(idmun, iddep, nombre) values(114,27,'tasco');
insert into mun(idmun, iddep, nombre) values(505,27,'tenza');
insert into mun(idmun, iddep, nombre) values(1167,27,'tibana');
insert into mun(idmun, iddep, nombre) values(380,27,'tibasosa');
insert into mun(idmun, iddep, nombre) values(1075,27,'tinjaca');
insert into mun(idmun, iddep, nombre) values(49,27,'tipacoque');
insert into mun(idmun, iddep, nombre) values(429,27,'toca');
insert into mun(idmun, iddep, nombre) values(1086,27,'togui');
insert into mun(idmun, iddep, nombre) values(830,27,'topaga');
insert into mun(idmun, iddep, nombre) values(1016,27,'tota');
insert into mun(idmun, iddep, nombre) values(1082,27,'tunja');
insert into mun(idmun, iddep, nombre) values(562,27,'tunungua');
insert into mun(idmun, iddep, nombre) values(986,27,'turmeque');
insert into mun(idmun, iddep, nombre) values(324,27,'tuta');
insert into mun(idmun, iddep, nombre) values(778,27,'tutaz�');
insert into mun(idmun, iddep, nombre) values(285,27,'umbita');
insert into mun(idmun, iddep, nombre) values(719,27,'ventaquemada');
insert into mun(idmun, iddep, nombre) values(384,27,'villa de leyva');
insert into mun(idmun, iddep, nombre) values(909,27,'viracacha');
insert into mun(idmun, iddep, nombre) values(1023,27,'zetaquira');
insert into mun(idmun, iddep, nombre) values(449,10,'aguadas');
insert into mun(idmun, iddep, nombre) values(268,10,'anserma');
insert into mun(idmun, iddep, nombre) values(1138,10,'aranzazu');
insert into mun(idmun, iddep, nombre) values(759,10,'arauca');
insert into mun(idmun, iddep, nombre) values(541,10,'arboleda');
insert into mun(idmun, iddep, nombre) values(672,10,'belalcazar');
insert into mun(idmun, iddep, nombre) values(567,10,'bolivia');
insert into mun(idmun, iddep, nombre) values(670,10,'chinchina');
insert into mun(idmun, iddep, nombre) values(970,10,'filadelfia');
insert into mun(idmun, iddep, nombre) values(91,10,'florencia');
insert into mun(idmun, iddep, nombre) values(557,10,'la dorada');
insert into mun(idmun, iddep, nombre) values(440,10,'la merced');
insert into mun(idmun, iddep, nombre) values(1093,10,'manizales');
insert into mun(idmun, iddep, nombre) values(223,10,'manzanares');
insert into mun(idmun, iddep, nombre) values(633,10,'marmato');
insert into mun(idmun, iddep, nombre) values(825,10,'marquetalia');
insert into mun(idmun, iddep, nombre) values(621,10,'marulanda');
insert into mun(idmun, iddep, nombre) values(891,10,'montebonito');
insert into mun(idmun, iddep, nombre) values(703,10,'neira');
insert into mun(idmun, iddep, nombre) values(731,10,'norcasia');
insert into mun(idmun, iddep, nombre) values(203,10,'norcasia');
insert into mun(idmun, iddep, nombre) values(1135,10,'pacora');
insert into mun(idmun, iddep, nombre) values(372,10,'palestina');
insert into mun(idmun, iddep, nombre) values(148,10,'pensilvania');
insert into mun(idmun, iddep, nombre) values(588,10,'riosucio');
insert into mun(idmun, iddep, nombre) values(1014,10,'risaralda');
insert into mun(idmun, iddep, nombre) values(680,10,'salamina');
insert into mun(idmun, iddep, nombre) values(360,10,'samana');
insert into mun(idmun, iddep, nombre) values(503,10,'san felix');
insert into mun(idmun, iddep, nombre) values(981,10,'san jose');
insert into mun(idmun, iddep, nombre) values(36,10,'san jose de risaralda');
insert into mun(idmun, iddep, nombre) values(444,10,'supia');
insert into mun(idmun, iddep, nombre) values(385,10,'victoria');
insert into mun(idmun, iddep, nombre) values(887,10,'villamaria');
insert into mun(idmun, iddep, nombre) values(896,10,'viterbo');
insert into mun(idmun, iddep, nombre) values(1088,30,'albania');
insert into mun(idmun, iddep, nombre) values(1078,30,'belen de los andaquies');
insert into mun(idmun, iddep, nombre) values(682,30,'cartagena del chaira');
insert into mun(idmun, iddep, nombre) values(591,30,'curillo');
insert into mun(idmun, iddep, nombre) values(971,30,'el doncello');
insert into mun(idmun, iddep, nombre) values(180,30,'el paujil');
insert into mun(idmun, iddep, nombre) values(1084,30,'florencia');
insert into mun(idmun, iddep, nombre) values(743,30,'guacamayas');
insert into mun(idmun, iddep, nombre) values(931,30,'la montañita');
insert into mun(idmun, iddep, nombre) values(312,30,'maticuro');
insert into mun(idmun, iddep, nombre) values(35,30,'milan');
insert into mun(idmun, iddep, nombre) values(132,30,'morelia');
insert into mun(idmun, iddep, nombre) values(111,30,'puerto rico');
insert into mun(idmun, iddep, nombre) values(1220,30,'san jose de la fragua');
insert into mun(idmun, iddep, nombre) values(902,30,'san jose fragua');
insert into mun(idmun, iddep, nombre) values(54,30,'san vicente del caguan');
insert into mun(idmun, iddep, nombre) values(236,30,'solano');
insert into mun(idmun, iddep, nombre) values(876,30,'solita');
insert into mun(idmun, iddep, nombre) values(819,30,'solita');
insert into mun(idmun, iddep, nombre) values(939,30,'valparaiso');
insert into mun(idmun, iddep, nombre) values(65,35,'aguazul');
insert into mun(idmun, iddep, nombre) values(320,35,'chameza');
insert into mun(idmun, iddep, nombre) values(39,35,'hato corozal');
insert into mun(idmun, iddep, nombre) values(5,35,'la salina');
insert into mun(idmun, iddep, nombre) values(921,35,'mani');
insert into mun(idmun, iddep, nombre) values(648,35,'monterrey');
insert into mun(idmun, iddep, nombre) values(1130,35,'nunchia');
insert into mun(idmun, iddep, nombre) values(368,35,'orocue');
insert into mun(idmun, iddep, nombre) values(1050,35,'paz de ariporo');
insert into mun(idmun, iddep, nombre) values(345,35,'pore');
insert into mun(idmun, iddep, nombre) values(1112,35,'recetor');
insert into mun(idmun, iddep, nombre) values(426,35,'sabanalarga');
insert into mun(idmun, iddep, nombre) values(1031,35,'sacama');
insert into mun(idmun, iddep, nombre) values(348,35,'san luis de palenque');
insert into mun(idmun, iddep, nombre) values(214,35,'tamara');
insert into mun(idmun, iddep, nombre) values(855,35,'tauramena');
insert into mun(idmun, iddep, nombre) values(1072,35,'trinidad');
insert into mun(idmun, iddep, nombre) values(705,35,'villanueva');
insert into mun(idmun, iddep, nombre) values(1085,35,'yopal');
insert into mun(idmun, iddep, nombre) values(1005,18,'almaguer');
insert into mun(idmun, iddep, nombre) values(1137,18,'argelia');
insert into mun(idmun, iddep, nombre) values(995,18,'balboa');
insert into mun(idmun, iddep, nombre) values(1149,18,'bolivar');
insert into mun(idmun, iddep, nombre) values(398,18,'buenos aires');
insert into mun(idmun, iddep, nombre) values(472,18,'cajibio');
insert into mun(idmun, iddep, nombre) values(137,18,'caldono');
insert into mun(idmun, iddep, nombre) values(77,18,'caloto');
insert into mun(idmun, iddep, nombre) values(881,18,'corinto');
insert into mun(idmun, iddep, nombre) values(178,18,'el tambo');
insert into mun(idmun, iddep, nombre) values(1059,18,'florencia');
insert into mun(idmun, iddep, nombre) values(459,18,'guapi');
insert into mun(idmun, iddep, nombre) values(182,18,'inza');
insert into mun(idmun, iddep, nombre) values(786,18,'jambalo');
insert into mun(idmun, iddep, nombre) values(112,18,'la sierra');
insert into mun(idmun, iddep, nombre) values(165,18,'la vega');
insert into mun(idmun, iddep, nombre) values(627,18,'lopez de micay');
insert into mun(idmun, iddep, nombre) values(7,18,'mercaderes');
insert into mun(idmun, iddep, nombre) values(1018,18,'miranda');
insert into mun(idmun, iddep, nombre) values(282,18,'morales');
insert into mun(idmun, iddep, nombre) values(1141,18,'padilla');
insert into mun(idmun, iddep, nombre) values(334,18,'paez');
insert into mun(idmun, iddep, nombre) values(911,18,'patia (el bordo)');
insert into mun(idmun, iddep, nombre) values(107,18,'piamonte');
insert into mun(idmun, iddep, nombre) values(461,18,'piendamo');
insert into mun(idmun, iddep, nombre) values(1117,18,'popayan');
insert into mun(idmun, iddep, nombre) values(555,18,'puerto tejada');
insert into mun(idmun, iddep, nombre) values(836,18,'purace');
insert into mun(idmun, iddep, nombre) values(233,18,'rosas');
insert into mun(idmun, iddep, nombre) values(376,18,'san sebastian');
insert into mun(idmun, iddep, nombre) values(1017,18,'santa rosa');
insert into mun(idmun, iddep, nombre) values(493,18,'santander');
insert into mun(idmun, iddep, nombre) values(994,18,'santander de quilichao');
insert into mun(idmun, iddep, nombre) values(747,18,'siberia');
insert into mun(idmun, iddep, nombre) values(782,18,'silvia');
insert into mun(idmun, iddep, nombre) values(122,18,'sotara');
insert into mun(idmun, iddep, nombre) values(564,18,'suarez');
insert into mun(idmun, iddep, nombre) values(818,18,'sucre');
insert into mun(idmun, iddep, nombre) values(524,18,'timba');
insert into mun(idmun, iddep, nombre) values(536,18,'timbio');
insert into mun(idmun, iddep, nombre) values(292,18,'timbiqui');
insert into mun(idmun, iddep, nombre) values(447,18,'toribio');
insert into mun(idmun, iddep, nombre) values(412,18,'totoro');
insert into mun(idmun, iddep, nombre) values(361,18,'villa rica');
insert into mun(idmun, iddep, nombre) values(280,37,'aguachica');
insert into mun(idmun, iddep, nombre) values(27,37,'astrea');
insert into mun(idmun, iddep, nombre) values(977,37,'becerril');
insert into mun(idmun, iddep, nombre) values(663,37,'bosconia');
insert into mun(idmun, iddep, nombre) values(98,37,'chimichagua');
insert into mun(idmun, iddep, nombre) values(813,37,'chiriguana');
insert into mun(idmun, iddep, nombre) values(450,37,'codazzi');
insert into mun(idmun, iddep, nombre) values(253,37,'curumani');
insert into mun(idmun, iddep, nombre) values(795,37,'el copey');
insert into mun(idmun, iddep, nombre) values(1052,37,'el paso');
insert into mun(idmun, iddep, nombre) values(1001,37,'gamarra');
insert into mun(idmun, iddep, nombre) values(340,37,'gonzalez');
insert into mun(idmun, iddep, nombre) values(817,37,'la gloria');
insert into mun(idmun, iddep, nombre) values(215,37,'la jagua de ibirico');
insert into mun(idmun, iddep, nombre) values(212,37,'la paz');
insert into mun(idmun, iddep, nombre) values(263,37,'manaure balcon del cesar');
insert into mun(idmun, iddep, nombre) values(335,37,'pailitas');
insert into mun(idmun, iddep, nombre) values(296,37,'pelaya');
insert into mun(idmun, iddep, nombre) values(745,37,'pueblo bello');
insert into mun(idmun, iddep, nombre) values(156,37,'pueblo bello');
insert into mun(idmun, iddep, nombre) values(587,37,'rio de oro');
insert into mun(idmun, iddep, nombre) values(410,37,'san alberto');
insert into mun(idmun, iddep, nombre) values(1133,37,'san diego');
insert into mun(idmun, iddep, nombre) values(294,37,'san martin');
insert into mun(idmun, iddep, nombre) values(1056,37,'spokane');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1008,37,'TAMALAMEQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1106,37,'VALLEDUPAR');

INSERT INTO mun(idmun, iddep, nombre) VALUES(59,22,'ACANDI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(849,22,'ALTO BAUDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(535,22,'ANDAGOYA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1136,22,'ATRATO (YUTO)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(220,22,'BAGADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(993,22,'BAHIA SOLANO (MUTIS)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(141,22,'BAJO BAUDO (PIZARRO)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(250,22,'BAJO SAN JUAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1,22,'BELEN DE BAJIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(169,22,'BOJAYA (BELLAVISTA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(327,22,'CANTON DE SAN PABLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1214,22,'CARMEN DEL DARIEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1216,22,'CERTEGUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(559,22,'CONDOTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(369,22,'DARIEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(354,22,'EL CARMEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1047,22,'EL LITORAL DEL SAN JUAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(341,22,'ISTMINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(871,22,'JURADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(622,22,'LLORO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(239,22,'MEDIO ATRATO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1070,22,'MEDIO BAUDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1218,22,'MEDIO SAN JUAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(186,22,'NOVITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(205,22,'NUQUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1095,22,'QUIBDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1217,22,'RIO IRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(845,22,'RIO QUITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(660,22,'RIOSUCIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(953,22,'SAN JOSE DEL PALMAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(740,22,'SIPI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1009,22,'TADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1090,22,'UNGUIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(51,22,'UNION PANAMERICANA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(668,7,'AYAPEL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(146,7,'BUENAVISTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(171,7,'CANALETE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(651,7,'CERETE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(746,7,'CERROMATOSO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(794,7,'CHIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(827,7,'CHINU');
INSERT INTO mun(idmun, iddep, nombre) VALUES(484,7,'CIENAGA DE ORO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(424,7,'COTORRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(433,7,'LA APARTADA (LA FRONTERA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(857,7,'LORICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(880,7,'LOS CORDOBAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(422,7,'MO?ITOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(753,7,'MOMIL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(244,7,'MONTELIBANO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1040,7,'MONTERIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(508,7,'PLANETA RICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(157,7,'PUEBLO NUEVO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(976,7,'PUERTO ESCONDIDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(963,7,'PUERTO LIBERTADOR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(639,7,'PURISIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(952,7,'SAHAGUN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(835,7,'SAN ANDRES SOTAVENTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(75,7,'SAN ANTERO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(990,7,'SAN BERNARDO DEL VIENTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(875,7,'SAN CARLOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(613,7,'SAN PELAYO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(529,7,'TIERRALTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(80,7,'VALENCIA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(1026,39,'AGUA DE DIOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(464,39,'ALBAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(646,39,'ANAPOIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1166,39,'ANOLAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(733,39,'APULO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(823,39,'ARBELAEZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(9,39,'BELTRAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(726,39,'BITUIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(279,39,'BOGOTA, D.C.');
INSERT INTO mun(idmun, iddep, nombre) VALUES(168,39,'BOJACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(333,39,'CABRERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(725,39,'CACHIPAY');
INSERT INTO mun(idmun, iddep, nombre) VALUES(678,39,'CAJICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(950,39,'CAPARRAPI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(401,39,'CAQUEZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(518,39,'CARMEN DE CARUPA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(792,39,'CHAGUANI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(99,39,'CHIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(814,39,'CHIPAQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(275,39,'CHOACHI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(693,39,'CHOCONTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(630,39,'COGUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1058,39,'COTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(326,39,'CUCUNUBA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(568,39,'CUMACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(392,39,'EL COLEGIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(475,39,'EL PEÑON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(271,39,'EL ROSAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(441,39,'FACATATIVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1114,39,'FOMEQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(453,39,'FOSCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(446,39,'FUNZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(252,39,'FUQUENE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1060,39,'FUSAGASUGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(590,39,'GACHALA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(980,39,'GACHANCIPA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(751,39,'GACHETA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(176,39,'GAMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(455,39,'GIRARDOT');
INSERT INTO mun(idmun, iddep, nombre) VALUES(415,39,'GRANADA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(686,39,'GUACHETA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1103,39,'GUADUAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(677,39,'GUASCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(601,39,'GUATAQUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(370,39,'GUATAVITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(918,39,'GUAYABAL DE SIQUIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(558,39,'GUAYABETAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(402,39,'GUTIERREZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(927,39,'JERUSALEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(869,39,'JUNIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(605,39,'LA CALERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(958,39,'LA MESA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(907,39,'LA PALMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(162,39,'LA PE?A');
INSERT INTO mun(idmun, iddep, nombre) VALUES(428,39,'LA VEGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(383,39,'LENGUAZAQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(29,39,'MACHETA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1074,39,'MADRID');
INSERT INTO mun(idmun, iddep, nombre) VALUES(806,39,'MANTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(640,39,'MEDINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(281,39,'MOSQUERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(853,39,'NARIÑO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(701,39,'NEMOCON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(32,39,'NILO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(61,39,'NIMAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(187,39,'NOCAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1134,39,'PACHO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(43,39,'PAIME');
INSERT INTO mun(idmun, iddep, nombre) VALUES(373,39,'PANDI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(23,39,'PARATEBUENO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1168,39,'PASCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(544,39,'POR DEFINIR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(88,39,'PUERTO SALGAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(964,39,'PULI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(110,39,'QUEBRADANEGRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(947,39,'QUETAME');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1151,39,'QUIPILE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(723,39,'RICAURTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1043,39,'SAN ANTONIO TEQUENDAMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(249,39,'SAN BERNARDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(711,39,'SAN CAYETANO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(190,39,'SAN FRANCISCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(359,39,'SAN JUAN DE RIO SECO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(331,39,'SASAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1020,39,'SESQUILE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(598,39,'SIBATE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(785,39,'SILVANIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(762,39,'SIMIJACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1163,39,'SOACHA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(966,39,'SOPO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1080,39,'SUBACHOQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(810,39,'SUESCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(445,39,'SUPATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1102,39,'SUSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(848,39,'SUTATAUSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(820,39,'TABIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(901,39,'TAUSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(767,39,'TENA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(277,39,'TENJO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(314,39,'TIBACUY');
INSERT INTO mun(idmun, iddep, nombre) VALUES(530,39,'TIBIRITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(543,39,'TOCAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1146,39,'TOCANCIPA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(260,39,'TOPAIPI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(779,39,'UBALA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1002,39,'UBAQUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(230,39,'UBATE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(362,39,'UNE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1000,39,'USME');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1097,39,'UTICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(585,39,'VENECIA (OSPINA PEREZ)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(798,39,'VERGARA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(386,39,'VIANI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(134,39,'VILLAGOMEZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(886,39,'VILLAPINZON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(860,39,'VILLETA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(727,39,'VIOTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(19,39,'YACOPI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(310,39,'ZIPACON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(526,39,'ZIPAQUIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(200,12,'BARRANCO MINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(116,12,'CACAHUAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1036,12,'INIRIDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(17,12,'LA GUADALUPE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1219,12,'MAPIRIPANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(749,12,'MIRAFLORES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1057,12,'MORICHAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1003,12,'PANA PANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(452,12,'PUERTO COLOMBIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(771,12,'SAN FELIPE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1209,8,'ALBANIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(865,8,'BARRANCAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(173,8,'DIBULLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(160,8,'DISTRACCION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(397,8,'EL MOLINO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1113,8,'FONSECA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(619,8,'HATONUEVO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(808,8,'LA JAGUA DEL PILAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1073,8,'MAICAO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(131,8,'MANAURE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(758,8,'PUERTO BOLIVAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1037,8,'RIOHACHA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(510,8,'SAN JUAN DEL CESAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(477,8,'URIBIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(78,8,'URUMITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(730,8,'VILLANUEVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(351,13,'CALAMAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(850,13,'EL RETORNO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(629,13,'MIRAFLORES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(202,13,'MORICHAL VIEJO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(664,13,'PUERTO ARTURO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1091,13,'SAN JOSE DE GUAVIARE');

INSERT INTO mun(idmun, iddep, nombre) VALUES(81,38,'ACEVEDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(451,38,'AGRADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(695,38,'AIPE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(241,38,'ALGECIRAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(983,38,'ALTAMIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(867,38,'BARAYA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(735,38,'CAMPOALEGRE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(358,38,'COLOMBIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(63,38,'ELIAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(184,38,'GARZON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(4,38,'GIGANTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(199,38,'GUADALUPE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(288,38,'HOBO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(600,38,'IQUIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(197,38,'ISNOS(SAN JOSE DE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(620,38,'LA ARGENTINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(33,38,'LA PLATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(854,38,'NATAGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1116,38,'NEIVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(329,38,'OPORAPA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(44,38,'PAICOL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(371,38,'PALERMO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(25,38,'PALESTINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(462,38,'PITAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1145,38,'PITALITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(696,38,'RIVERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(915,38,'SALADOBLANCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1147,38,'SAN AGUSTIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(594,38,'SANTA MARIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(322,38,'SUAZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(900,38,'TARQUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(276,38,'TELLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(596,38,'TERUEL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(768,38,'TESALIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(528,38,'TIMANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(742,38,'VEGA LARGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1067,38,'VILLAVIEJA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(20,38,'YAGUARA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(394,40,'ALGARROBO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(822,40,'ARACATACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(159,40,'ARIGUANI (EL DIFICIL)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(437,40,'CERRO SAN ANTONIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(208,40,'CHIVOLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(485,40,'CIENAGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(560,40,'CONCORDIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(355,40,'EL BANCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(474,40,'EL PIÑON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(95,40,'EL RETEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(251,40,'FUNDACION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(457,40,'GUAMAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1211,40,'NUEVA GRANADA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(149,40,'PEDRAZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(838,40,'PIJIÑO DEL CARMEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1144,40,'PIVIJAY');
INSERT INTO mun(idmun, iddep, nombre) VALUES(507,40,'PLATO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(120,40,'PUEBLO VIEJO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(720,40,'REMOLINO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(913,40,'SABANAS DE SAN ANGEL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(987,40,'SALAMINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(346,40,'SAN SEBASTIAN BUENAVISTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(342,40,'SAN ZENON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(189,40,'SANTA ANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1212,40,'SANTA BARBARA DE PINTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1108,40,'SANTA MARTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(763,40,'SITIONUEVO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(512,40,'TENERIFE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1210,40,'ZAPAYAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(313,40,'ZONA BANANERA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(82,26,'ACACIAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(399,26,'BARRANCA DE UPIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(308,26,'CABUYARO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(681,26,'CASTILLA LA NUEVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(611,26,'CUBARRAL (SAN LUIS DE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(486,26,'CUMARAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(353,26,'EL CALVARIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(41,26,'EL CASTILLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(895,26,'EL DORADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(833,26,'FUENTE DE ORO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(916,26,'GRANADA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(420,26,'GUAMAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(434,26,'LA MACARENA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(417,26,'LA URIBE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(216,26,'LEJANIAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(349,26,'MAPIRIPAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(748,26,'MEDELLIN DEL ARIARI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1076,26,'MESETAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(8,26,'PUERTO CONCORDIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(152,26,'PUERTO GAITAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(28,26,'PUERTO LLERAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(550,26,'PUERTO LOPEZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(151,26,'PUERTO RICO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(690,26,'RESTREPO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(775,26,'SAN CARLOS DE GUAROA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(842,26,'SAN JUAN DE ARAMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(642,26,'SAN JUANITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(578,26,'SAN MARTIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1096,26,'UPIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1065,26,'UPIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1081,26,'VILLAVICENCIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(547,26,'VISTA HERMOSA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(463,19,'ALBAN (SAN JOSE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1006,19,'ALDANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(303,19,'ANCUYA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(533,19,'ARBOLEDA (BERRUECOS)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(144,19,'BARBACOAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(616,19,'BELEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(396,19,'BUESACO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(938,19,'CHACHAGUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(117,19,'COLON (GENOVA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(991,19,'CONSACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(809,19,'CONTADERO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(490,19,'CORDOBA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(300,19,'CUASPUD (CARLOSAMA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1142,19,'CUMBAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(922,19,'CUMBITARA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1051,19,'EL CHARCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1164,19,'EL PENOL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(179,19,'EL ROSARIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(476,19,'EL TABLON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(272,19,'EL TAMBO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(801,19,'FRANCISCO PIZARRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(832,19,'FUNES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(684,19,'GUACHUCAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1104,19,'GUAITARILLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(797,19,'GUALMATAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(581,19,'ILES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(286,19,'IMUES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(466,19,'IPIALES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(618,19,'LA CRUZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1150,19,'LA FLORIDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1121,19,'LA LLANADA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(319,19,'LA TOLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(805,19,'LA UNION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(55,19,'LEIVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(514,19,'LINARES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(623,19,'LOS ANDES (SOTOMAYOR)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(736,19,'MAGUI (PAYAN)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(118,19,'MALLAMA (PIEDRANCHA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(255,19,'MOSQUERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(378,19,'OLAYA HERRERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(586,19,'OSPINA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1038,19,'PASTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(655,19,'POLICARPA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(129,19,'POTOSI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(961,19,'PROVIDENCIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(554,19,'PUERRES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(800,19,'PUPIALES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(724,19,'RICAURTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(210,19,'ROBERTO PAYAN (SAN JOSE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(874,19,'SAMANIEGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(30,19,'SAN BERNARDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(270,19,'SAN LORENZO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(375,19,'SAN PABLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(941,19,'SAN PEDRO DE CARTAGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(843,19,'SANDONA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(812,19,'SANTA BARBARA (ISCUANDE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(73,19,'SANTACRUZ (GUACHAVES)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(492,19,'SAPUYES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(972,19,'TAMINANGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(113,19,'TANGUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(985,19,'TUMACO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(698,19,'TUQUERRES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(11,19,'YACUANQUER');

INSERT INTO mun(idmun, iddep, nombre) VALUES(209,11,'ABREGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(534,11,'ARBOLEDAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(167,11,'BOCHALEMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(997,11,'BUCARASICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(920,11,'CACHIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(38,11,'CACOTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(47,11,'CHINACOTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(669,11,'CHITAGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(356,11,'CONVENCION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1128,11,'CUCUTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(610,11,'CUCUTILLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1044,11,'DURANIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(391,11,'EL CARMEN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1053,11,'EL TARRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(525,11,'EL ZULIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(750,11,'GIBRALTAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(910,11,'GRAMALOTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(975,11,'HACARI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(657,11,'HERRAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1100,11,'LA ESPERANZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(570,11,'LA GABARRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(163,11,'LA PLAYA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(93,11,'LA VEGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(604,11,'LABATECA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(890,11,'LAS MERCEDES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(56,11,'LOS PATIOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(626,11,'LOURDES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(929,11,'MUTISCUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(608,11,'OCAÑA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(42,11,'PAMPLONA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(802,11,'PAMPLONITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1189,11,'POR DEFINIR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(856,11,'PUERTO SANTANDER');
INSERT INTO mun(idmun, iddep, nombre) VALUES(732,11,'RAGONVALIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(914,11,'SALAZAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(862,11,'SAN CALIXTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(497,11,'SAN CAYETANO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(774,11,'SANTIAGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(496,11,'SARDINATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(783,11,'SILOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1089,11,'TEORAMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(50,11,'TIBU');
INSERT INTO mun(idmun, iddep, nombre) VALUES(831,11,'TOLEDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(133,11,'VILLA CARO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(729,11,'VILLA ROSARIO');

INSERT INTO mun(idmun, iddep, nombre) VALUES(667,2,'COLON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1029,2,'MOCOA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1111,2,'ORITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(153,2,'PUERTO ASIS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(741,2,'PUERTO CAICEDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(722,2,'PUERTO GUZMAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(552,2,'PUERTO LEGUIZAMO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(22,2,'SAN FRANCISCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1024,2,'SAN MIGUEL (LA DORADA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(121,2,'SANTIAGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(826,2,'SIBUNDOY');
INSERT INTO mun(idmun, iddep, nombre) VALUES(879,2,'VALLE DEL GUAMEZ (LA HORMIGA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(12,2,'VILLA GARZON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1094,20,'ARMENIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(468,20,'BUENAVISTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(473,20,'CALARCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(708,20,'CIRCASIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(859,20,'CORDOBA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(968,20,'FILANDIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(597,20,'GENOVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(109,20,'LA TEBAIDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(634,20,'MONTENEGRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(435,20,'PIJAO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(949,20,'QUIMBAYA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(933,20,'SALENTO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(978,21,'APIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(992,21,'BALBOA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(673,21,'BELEN DE UMBRIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(207,21,'DOS QUEBRADAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(456,21,'GUATICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(816,21,'LA CELIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(217,21,'LA VIRGINIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(706,21,'MARSELLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(765,21,'MISTRATO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1110,21,'PEREIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(86,21,'PUEBLO RICO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(948,21,'QUINCHIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(166,21,'SAN ANTONIO DEL CHAMI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(482,21,'SANTA ROSA DE CABAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(269,21,'SANTUARIO');

INSERT INTO mun(idmun, iddep, nombre) VALUES(839,28,'PROVIDENCIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1107,28,'SAN ANDRES');

INSERT INTO mun(idmun, iddep, nombre) VALUES(448,32,'AGUADA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(242,32,'ALBANIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(532,32,'ARATOCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(100,32,'BARBOSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(145,32,'BARICHARA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(548,32,'BARRANCABERMEJA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1062,32,'BETULIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(712,32,'BOLIVAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1083,32,'BUCARAMANGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(653,32,'CABRERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(766,32,'CALIFORNIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1157,32,'CAPITANEJO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(246,32,'CARCASI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(566,32,'CENTRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(406,32,'CEPITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(649,32,'CERRITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1162,32,'CHARALA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1010,32,'CHARTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(256,32,'CHIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(868,32,'CHIPATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(709,32,'CIMITARRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(955,32,'CONCEPCION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(776,32,'CONFINES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(721,32,'CONTRATACION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(580,32,'COROMORO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(381,32,'CURITI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(715,32,'EL CARMEN DE CHUCURI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(352,32,'EL GUACAMAYO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1048,32,'EL PEÑON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(737,32,'EL PLAYON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(480,32,'ENCINO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(688,32,'ENCISO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(297,32,'FLORIAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(959,32,'FLORIDABLANCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(224,32,'GALAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(183,32,'GAMBITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(454,32,'GIRON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(419,32,'GUACA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1105,32,'GUADALUPE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(676,32,'GUAPOTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(575,32,'GUAVATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(781,32,'GUEPSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1011,32,'HATO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(925,32,'JESUS MARIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(416,32,'JORDAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(602,32,'LA BELLEZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(164,32,'LA PAZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1122,32,'LANDAZURI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(755,32,'LEBRIJA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(624,32,'LOS SANTOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(262,32,'MACARAVITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1159,32,'MALAGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(824,32,'MATANZA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(752,32,'MOGOTES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(85,32,'MOLAGAVITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(609,32,'OCAMONTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(421,32,'OIBA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(739,32,'ONZAGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1153,32,'PALMAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(374,32,'PALMAS SOCORRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(106,32,'PARAMO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(227,32,'PIEDECUESTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(67,32,'PINCHOTE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(89,32,'PUENTE NACIONAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(553,32,'PUERTO PARRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(607,32,'PUERTO WILCHES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(659,32,'RIONEGRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(431,32,'SABANA DE TORRES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(892,32,'SAN ANDRES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(498,32,'SAN BENITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(744,32,'SAN FRANCISCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(571,32,'SAN GIL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(483,32,'SAN JOAQUIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(231,32,'SAN JOSE DE MIRANDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(94,32,'SAN JOSE DE S.');
INSERT INTO mun(idmun, iddep, nombre) VALUES(614,32,'SAN MIGUEL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(577,32,'SAN VICENTE DE CHUCURI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(232,32,'SANTA BARBARA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(494,32,'SANTA HELENA DEL OPON');
INSERT INTO mun(idmun, iddep, nombre) VALUES(761,32,'SIMACOTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(16,32,'SOCORRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(295,32,'SUAITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(194,32,'SUCRE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(565,32,'SURATA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(828,32,'TONA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(79,32,'VALLE DE SAN JOSE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(716,32,'VELEZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(387,32,'VETAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1066,32,'VILLANUEVA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(407,32,'ZAPATOCA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(390,31,'BUENAVISTA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(309,31,'CAIMITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(367,31,'CHALAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(192,31,'COLOSO (RICAURTE)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(489,31,'COROZAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1213,31,'EL ROBLE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(714,31,'GALERAS (NUEVA GRANADA)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1045,31,'GUARANDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(218,31,'LA UNION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(625,31,'LOS PALMITOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(161,31,'MAJAGUAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(254,31,'MORROA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(652,31,'OVEJAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1068,31,'PALMITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(863,31,'SAMPUES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(872,31,'SAN BENITO ABAD');
INSERT INTO mun(idmun, iddep, nombre) VALUES(935,31,'SAN JUAN DE BETULIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(273,31,'SAN MARCOS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1064,31,'SAN ONOFRE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(522,31,'SAN PEDRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(158,31,'SINCE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1127,31,'SINCELEJO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(702,31,'SUCRE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(829,31,'TOLU');
INSERT INTO mun(idmun, iddep, nombre) VALUES(258,31,'TOLUVIEJO');

INSERT INTO mun(idmun, iddep, nombre) VALUES(760,9,'ALPUJARRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(984,9,'ALVARADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(393,9,'AMBALEMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(647,9,'ANAIME');
INSERT INTO mun(idmun, iddep, nombre) VALUES(366,9,'ANZOATEGUI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(789,9,'ARMERO (GUAYABAL)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(509,9,'ATACO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(757,9,'CADIZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(307,9,'CAJAMARCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(956,9,'CARMEN DE APICALA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(247,9,'CASABIANCA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(793,9,'CHAPARRAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(628,9,'COELLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(579,9,'COYAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(487,9,'CUNDAY');
INSERT INTO mun(idmun, iddep, nombre) VALUES(388,9,'DOLORES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(96,9,'ESPINAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(894,9,'FALAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(974,9,'FLANDES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(364,9,'FRESNO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(502,9,'GAITANA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(198,9,'GUAMO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(92,9,'HERRERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(656,9,'HERVEO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(289,9,'HONDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1039,9,'IBAGUE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(582,9,'ICONONZO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(906,9,'JUNIN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(229,9,'LERIDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(513,9,'LIBANO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(264,9,'MARIQUITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(311,9,'MELGAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(821,9,'MURILLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(852,9,'NATAGAIMA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(175,9,'ORTEGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(889,9,'PALO CABILDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(769,9,'PALOCABILDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(228,9,'PIEDRAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(506,9,'PLANADAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(37,9,'PLAYA RICA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(662,9,'PRADO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(799,9,'PURIFICACION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1061,9,'RIOBLANCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(235,9,'RONCESVALLES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(898,9,'ROVIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(954,9,'SALDA�A');
INSERT INTO mun(idmun, iddep, nombre) VALUES(989,9,'SAN ANTONIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(873,9,'SAN LUIS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(615,9,'SANTA ISABEL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(542,9,'SANTA TERESA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(700,9,'SANTIAGO PEREZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(293,9,'SUAREZ');
INSERT INTO mun(idmun, iddep, nombre) VALUES(546,9,'TRES ESQUINAS');
INSERT INTO mun(idmun, iddep, nombre) VALUES(140,9,'VALLE DE SAN JUAN');
INSERT INTO mun(idmun, iddep, nombre) VALUES(717,9,'VENADILLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(780,9,'VILLAHERMOSA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(885,9,'VILLARRICA');

INSERT INTO mun(idmun, iddep, nombre) VALUES(243,6,'ALCALA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(304,6,'ANDALUCIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(90,6,'ANSERMANUEVO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(772,6,'ARGELIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1148,6,'BOLIVAR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(999,6,'BUENAVENTURA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(469,6,'BUGA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(501,6,'BUGALAGRANDE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(539,6,'CAICEDONIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1120,6,'CALI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(679,6,'CALIMA (DARIEN)');
INSERT INTO mun(idmun, iddep, nombre) VALUES(471,6,'CANDELARIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1158,6,'CARTAGO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(923,6,'DAGUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(181,6,'EL AGUILA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(636,6,'EL CAIRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(71,6,'EL CERRITO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1049,6,'EL DOVIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(973,6,'FLORIDA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(3,6,'GINEBRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(460,6,'GUACARI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(784,6,'JAMUNDI');
INSERT INTO mun(idmun, iddep, nombre) VALUES(603,6,'LA CUMBRE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(213,6,'LA UNION');
INSERT INTO mun(idmun, iddep, nombre) VALUES(583,6,'LA VICTORIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(665,6,'OBANDO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(770,6,'PALMIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(661,6,'PRADERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(691,6,'RESTREPO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1015,6,'RIOFRIO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(234,6,'ROLDANILLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(834,6,'SAN PEDRO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1041,6,'SEVILLA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(259,6,'TORO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(127,6,'TRUJILLO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(467,6,'TULUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(363,6,'ULLOA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(302,6,'VERSALLES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(154,6,'VIJES');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1155,6,'YOTOCO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(523,6,'YUMBO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(409,6,'ZARZAL');
INSERT INTO mun(idmun, iddep, nombre) VALUES(438,34,'CARURU');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1119,34,'MITU');
INSERT INTO mun(idmun, iddep, nombre) VALUES(945,34,'PACOA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(443,34,'PAPUNAHUA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(403,34,'TARAIRA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(878,34,'YAVARATE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(195,4,'CUMARIBO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(365,4,'LA PRIMAVERA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(738,4,'NUEVA ANTIOQUIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(125,4,'POR DEFINIR');
INSERT INTO mun(idmun, iddep, nombre) VALUES(1092,4,'PUERTO CARREÑO');
INSERT INTO mun(idmun, iddep, nombre) VALUES(123,4,'SAN JOSE DE OCUNE');
INSERT INTO mun(idmun, iddep, nombre) VALUES(87,4,'SANTA RITA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(404,4,'SANTA ROSALIA');
INSERT INTO mun(idmun, iddep, nombre) VALUES(899,4,'SANTA ROSALIA');



