use bd_eros;
insert into dep(iddep, nombre) values(5,'Amazonas');
insert into dep(iddep, nombre) values(1,'Antioquia');
insert into dep(iddep, nombre) values(33,'Arauca');
insert into dep(iddep, nombre) values(36,'Atlantico');
insert into dep(iddep, nombre) values(29,'Bogota');
insert into dep(iddep, nombre) values(3,'Bolivar');
insert into dep(iddep, nombre) values(27,'Boyaca');
insert into dep(iddep, nombre) values(10,'Caldas');
insert into dep(iddep, nombre) values(30,'Caqueta');
insert into dep(iddep, nombre) values(35,'Casanare');
insert into dep(iddep, nombre) values(18,'Cauca');
insert into dep(iddep, nombre) values(37,'Cesar');
insert into dep(iddep, nombre) values(22,'Choco');
insert into dep(iddep, nombre) values(7,'Cordoba');
insert into dep(iddep, nombre) values(39,'Cundinamarca');
insert into dep(iddep, nombre) values(12,'Guainia');
insert into dep(iddep, nombre) values(8,'Guajira');
insert into dep(iddep, nombre) values(13,'Guaviare');
insert into dep(iddep, nombre) values(38,'Huila');
insert into dep(iddep, nombre) values(40,'Magdalena');
insert into dep(iddep, nombre) values(26,'Meta');
insert into dep(iddep, nombre) values(19,'Nariño');
insert into dep(iddep, nombre) values(11,'Norte santander');
insert into dep(iddep, nombre) values(2,'Putumayo');
insert into dep(iddep, nombre) values(20,'Quindio');
insert into dep(iddep, nombre) values(21,'Risaralda');
insert into dep(iddep, nombre) values(28,'San Andres');
insert into dep(iddep, nombre) values(32,'Santander');
insert into dep(iddep, nombre) values(31,'Sucre');
insert into dep(iddep, nombre) values(9,'Tolima');
insert into dep(iddep, nombre) values(6,'Valle');
insert into dep(iddep, nombre) values(34,'Vaupes');
insert into dep(iddep, nombre) values(4,'Vichada');
